services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/db/migrations:/app/db/migrations
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: Cotizacion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: L4z4r0$
    ports:
      - "5000:5432"
    volumes:
      - ./backend/db/postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    # El servicio del frontend de Angular
  frontend:
    build:
      context: ./frontend  # Asume que tu proyecto de Angular está en una carpeta 'frontend'
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge